version: "3.8"

services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_gdrive_api
    env_file:
      - .env # Load environment variables from .env file
    volumes:
      - ./backend:/app/backend # Mount backend code for development (optional for production)
      - ./data/vector_store:/app/data/vector_store # Persistent vector store
      - ./data/sample_documents:/app/data/sample_documents # Sample documents
      - ./logs:/app/logs # Persistent logs
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}" # Use API_PORT from .env, default to 8000
    command: >
      sh -c "
      python -m rag_system.utils.wait_for_system --timeout 60 &&
      uvicorn rag_system.api.app:app --host 0.0.0.0 --port ${API_PORT:-8000} --app-dir backend/
      "
    # healthcheck: # Basic healthcheck, can be more sophisticated
    #   test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-8000}/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    restart: unless-stopped
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

# To run: docker-compose up --build
# To access API docs: http://localhost:<API_PORT>/docs
# Ensure .env file is present in the root directory with necessary configurations.
