[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "frontend"

[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  python_runtime = "python3.9"

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/query"
  to = "/.netlify/functions/query"
  status = 200

[[redirects]]
  from = "/api/ingest"
  to = "/.netlify/functions/ingest"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200